apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gcloud
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/caramel-day-434618-t7/demo-ai-art-repo/demo-ai-site:latest